title: "SaTourN Mapping"
description: "Mapping zwischen SaTourN/eT4 und schema.org/ODTA"
markdown: kramdown
theme: null
plugins: []
# FÃ¼r Project Pages ggf. baseurl setzen, z.B. "/SaTourN"
baseurl: ""
url: ""
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - tools
